FROM gapsystem/gap-docker@sha256:adb744a07dfe5f4a0551e47cebda61bb323d5af7378d5e3d63474e49d9c6e05b

RUN sudo python3 -mpip install --no-cache \
    jupyterhub==1.0.* \
    jupyterlab==1.1.* \
    nbgitpuller
